name: Hwa
description: Hwa Messenger Prototype Application
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences:
  http:
  json_annotation:
  cached_network_image:
  rxdart:
  alphabet_list_scroll_view:
  faker:
  flutter_slidable:
  stomp:
  geolocator:
#  flutter_kakao_login:
#  flutter_facebook_login:
#  google_sign_in:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKR-Bold.otf
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Black.otf
        - asset: assets/fonts/NotoSansKR-Light.otf
        - asset: assets/fonts/NotoSansKR-Medium.otf
        - asset: assets/fonts/NotoSansKR-Thin.otf
    - family: NanumSquare
      fonts:
        - asset: assets/fonts/NanumSquare_acR.ttf
        - asset: assets/fonts/NanumSquare_acB.ttf
        - asset: assets/fonts/NanumSquare_acL.ttf
        - asset: assets/fonts/NanumSquare_acEB.ttf

  assets:
    - assets/images/logo.png
    - assets/images/icon/iconAttachCamera.png
    - assets/images/icon/iconAttachMore.png
    - assets/images/icon/iconBell.png
    - assets/images/icon/iconBounds.png
    - assets/images/icon/iconFold.png
    - assets/images/icon/iconLikeCount.png
    - assets/images/icon/iconPin.png
    - assets/images/icon/iconVideoPlay.png
    - assets/images/icon/iconViewCount.png
    - assets/images/icon/navIconHot.png
    - assets/images/icon/navIconNew.png
    - assets/images/icon/navIconPrev.png
    - assets/images/icon/navIconSearch.png
    - assets/images/icon/tabIconChat.png
    - assets/images/icon/tabIconChatActive.png
    - assets/images/icon/tabIconFriend.png
    - assets/images/icon/tabIconHwa.png
    - assets/images/icon/tabIconHwaActive.png
    - assets/images/background/bgMap.png

  uses-material-design: true


