name: Hwa
description: Hwa Messenger Prototype Application
version: 1.0.0+1

environment:
    sdk: ">=2.2.2 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    flutter_localizations:
        sdk: flutter
    flutter_cupertino_localizations:


    #채워주세요~~~ 쓸데없는거 지우게, indent 4칸으로 맞춰주세요
    ### Add by HS ###
    cupertino_icons: ^0.1.2
    intl:
    configurable_expansion_tile: ^1.0.0
    timeago: ^2.0.22                  # Get Time Ago
    lazy_load_scrollview: 1.0.1       # Lazy Loading
    sticky_headers: ^0.1.8+1          # For Friend List Alphabet Scroll (추후 삭제 예정)
    flutter_screenutil: ^0.7.0        # Screen Ratio
    catcher: ^0.2.8                   # Error View Management
    json_annotation:
    video_thumbnail: ^0.2.0           # Video Thumbnail
    video_player:                     # Video Player Added Header

    ### Add by HK ###
    dio: 3.0.8                        # Http, File Upload
    http:                             # Http
    cached_network_image: 2.0.0       # Image Cache
    firebase_messaging: ^6.0.9        # Firebase messaging
    web_socket_channel: ^1.0.13       # WebSocket
    geolocator: ^5.1.5                # Location
    image_picker: 0.6.3               # Image Picker
    photo_view: ^0.5.0                # Photo View
    easy_localization: 1.3.1          # localization(다국어)
    mime: ^0.9.6+3                    # Mime Type
    youtube_player_flutter: ^6.0.3+2  # Youtube
    path_provider: ^1.5.1             # file download

    ### Add by JH ###
    shared_preferences:             # SharedPreferences
    provider:                       # Provider

    ### Add by SH ###
    js: ^0.6.0
    kvsql: ^0.3.0
    sqlcool: ^4.2.0
    flutter_facebook_login: 3.0.0   # Social Login - Facebook
    google_sign_in: ^4.1.1          # Social Login - Google
    #flutter_kakao_login: "^0.5.0"  # Social Login - Kakao
    #kakao_flutter_sdk: ^0.3.2
    contacts_service: ^0.3.10


    ### BLE module ###
    hwa_beacon:
#        path: ./hwa_beacon-master
        git:
            url: https://github.com/leejaku17/hwa_beacon


    ### Comment-HS : 본인이 추가한 Package는 아니지만 아래 목록 검토 필요해보임 (몇몇개는 쓰이는 것들)
    alphabet_list_scroll_view:
    flutter_slidable:
    expandable: ^4.0.1
    fluttertoast: ^3.1.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: false
  image_path: "ios/Runner/Assets.xcassets/AppIcon.appiconset/ios-marketing.png"

flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 200
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        
    - family: NanumSquare
      fonts:
        - asset: assets/fonts/NanumSquare_acR.ttf
          weight: 400
        - asset: assets/fonts/NanumSquare_acB.ttf
          weight: 500
        - asset: assets/fonts/NanumSquare_acL.ttf
        - asset: assets/fonts/NanumSquare_acEB.ttf

  assets:
    #Common Image
    - assets/images/logo.png
    - assets/images/loginLogo.png
    - assets/images/splash.png
    - assets/images/businesscard.png
    - assets/images/bgGradeLogin.png
    - assets/images/bgGrade.png
    #Background Image
    - assets/images/background/noChatackgroundImg.png
    - assets/images/background/noRoomBackgroundImg.png
    - assets/images/background/noBleBackgroundImg.png
    - assets/images/background/noLocationBackgroundImg.png
    - assets/images/background/commonBackgroundImg.png
    - assets/images/background/noFriendImg.png
    #SNS Image
    - assets/images/sns/snsIconFacebook.png
    - assets/images/sns/snsIconGoogle.png
    - assets/images/sns/snsIconKakao.png
    #Ios launch Image
    - assets/images/iosLaunchScreen/hwaImage.png
    - assets/images/iosLaunchScreen/hwaImage.png
    - assets/images/iosLaunchScreen/visualImage.png
    #Icon Image
    - assets/images/icon/appIcon.jpg
    - assets/images/icon/appIcon2.png
    - assets/images/icon/crown.png
    - assets/images/icon/iconActionMenuOpen.png
    - assets/images/icon/iconAddress.png
    - assets/images/icon/iconAttachCamera.png
    - assets/images/icon/iconAttachCameraChat.png
    - assets/images/icon/iconAttachCard.png
    - assets/images/icon/iconAttachClose.png
    - assets/images/icon/iconAttachMore.png
    - assets/images/icon/iconAttachPhoto.png
    - assets/images/icon/iconAttachFold.png
    - assets/images/icon/iconBell.png
    - assets/images/icon/iconBlock.png
    - assets/images/icon/iconBounds.png
    - assets/images/icon/iconCar.png
    - assets/images/icon/iconClosePopup.png
    - assets/images/icon/iconDeleteSmall.png
    - assets/images/icon/iconDirectChat.png
    - assets/images/icon/iconEject.png
    - assets/images/icon/iconFold.png
    - assets/images/icon/iconLike.png
    - assets/images/icon/iconExit.png
    - assets/images/icon/iconExpand.png
    - assets/images/icon/iconHeartRed.png
    - assets/images/icon/iconLikeCount.png
    - assets/images/icon/iconMasterBadge.png
    - assets/images/icon/iconMore.png
    - assets/images/icon/iconMoreWhite.png
    - assets/images/icon/iconPin.png
    - assets/images/icon/iconRequest.png
    - assets/images/icon/iconRequestCalling.png
    - assets/images/icon/iconVideoPlay.png
    - assets/images/icon/iconViewCard.png
    - assets/images/icon/iconViewCount.png
    - assets/images/icon/iconWallet.png
    - assets/images/icon/iconLock.png
    - assets/images/icon/iconUnlock.png
    - assets/images/icon/iconUnfold.png
    - assets/images/icon/iconSendMessage.png
    - assets/images/icon/iconSetting.png
    - assets/images/icon/more.png
    - assets/images/icon/navIconHot.png
    - assets/images/icon/navIconClose.png
    - assets/images/icon/navIconDown.png
    - assets/images/icon/navIconNew.png
    - assets/images/icon/navIconPrev.png
    - assets/images/icon/navIconMenu.png
    - assets/images/icon/navIconSearch.png
    - assets/images/icon/navIconWrite.png
    - assets/images/icon/personIconColor.png
    - assets/images/icon/personIconGrey.png
    - assets/images/icon/photoProfileDefault.png
    - assets/images/icon/profile.png
    - assets/images/icon/profileSeticonBasic.png
    - assets/images/icon/setIcon.png
    - assets/images/icon/tabIconChat.png
    - assets/images/icon/tabIconChatActive.png
    - assets/images/icon/tabIconFriend.png
    - assets/images/icon/tabIconFriendActive.png
    - assets/images/icon/tabIconHwa.png
    - assets/images/icon/tabIconHwaActive.png
    - assets/images/icon/gpsIconConnected.png
    - assets/images/icon/bluetoothIconConnected.png
    - assets/images/icon/bluetoothIconUnconnected.png
    - assets/images/icon/thumbnailUnset1.png
    - assets/images/icon/thumbnailUnset2.png
    - assets/images/icon/iconRefresh.png
    - assets/images/icon/gpsIconUnconnected.png
    - assets/images/icon/howmanyIcon.png

    # langs
    - assets/langs/en.json
    - assets/langs/ko.json

  uses-material-design: true


